fun main(){
    //Exception

    val list= listOf<Int>(1,2)
    list[3]
}